services:
  - type: web
    name: masar-api
    env: node
    plan: free
    buildCommand: "npm install --include=dev && cd apps/api && npx prisma generate && npm run build"
    startCommand: "cd apps/api && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: PORT
        value: 3001
